language: c
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y build-essential make binutils gcc autoconf automake libtool pkg-config git libpcap-dev libgcrypt-dev libgpg-error-dev libjson-c-dev libmaxminddb-dev netcat-openbsd python3 python3-jsonschema
script:
- git clone https://github.com/ntop/nDPI.git
- cd nDPI &&
  git checkout a6029d250d9c5dd0d7346fe47de838c243c20cac &&
  ./autogen.sh --prefix=$(realpath ./_install) --with-sanitizer --with-only-libndpi &&
  make install -j4 &&
  cd ..
- make -f Makefile.old NDPI_WITH_GCRYPT=yes CUSTOM_LIBNDPI=./nDPI/_install/lib/libndpi.a ENABLE_DEBUG=yes ENABLE_SANITIZER=yes all examples
- env python3 --version
- test/run_tests.sh nDPI
- make -f Makefile.old clean
# pkg-config build
- PKG_CONFIG_PATH="$(realpath ./nDPI/_install/lib/pkgconfig)" make -f Makefile.old PKG_CONFIG_BIN=pkg-config ENABLE_DEBUG=yes ENABLE_SANITIZER=yes all examples
- ./nDPId-test || test $? -eq 1
- ./nDPId -h || test $? -eq 1
# cmake/pkg-config build
- mkdir -p build && cd build && PKG_CONFIG_PATH="$(realpath ../nDPI/_install/lib/pkgconfig)" cmake .. -DCMAKE_INSTALL_PREFIX=$(realpath ../_install) -DBUILD_EXAMPLES=ON -DENABLE_MEMORY_PROFILING=ON -DENABLE_SANITIZER=ON && make install
- cd build && ./nDPId-test || test $? -eq 1
- cd build && ./nDPId -h || test $? -eq 1
